# Steps involved in creating a neural network #

1) Define the model
2) Compile the model
3) Fit the model


In [25]:
# Import iris dataset #
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
Y = iris.target
# X = (x for x in X if Y!=2)
# Y = (y for y in Y if Y!=2)
# Convert to dataframes/ numpy arrays #
iris.data.shape
print(Y)


# Split the dataset into test and train datasets

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.60, random_state=0)

<generator object <genexpr> at 0x7f0d487441a8>


TypeError: Singleton array array(<generator object <genexpr> at 0x7f0d5a2cd410>, dtype=object) cannot be considered a valid collection.

In [22]:
### Logistic regression using DNN ###
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.utils import np_utils

import numpy
numpy.random.seed(7)

# Defining model #

model = Sequential()
model.add(Dense(1,input_dim=4,activation='sigmoid'))
# model.add(Dense(16,activation='sigmoid'))
# model.add(Dense(1,activation='sigmoid'))

# Compile the model #

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Fit the model #

model.fit(x_train, y_train, epochs=150, batch_size=10)
# model.summary()

# Precision #

# Confusion matrix #


# Evaluate the model #

scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))



Epoch 1/150
60/60 [==============================] - 0s 2ms/step - loss: 0.7497 - acc: 0.2833
Epoch 2/150
60/60 [==============================] - 0s 113us/step - loss: 0.7338 - acc: 0.2833
Epoch 3/150
60/60 [==============================] - 0s 83us/step - loss: 0.7146 - acc: 0.2833
Epoch 4/150
60/60 [==============================] - 0s 73us/step - loss: 0.6997 - acc: 0.2833
Epoch 5/150
60/60 [==============================] - 0s 107us/step - loss: 0.6845 - acc: 0.2833
Epoch 6/150
60/60 [==============================] - 0s 105us/step - loss: 0.6677 - acc: 0.2833
Epoch 7/150
60/60 [==============================] - 0s 111us/step - loss: 0.6531 - acc: 0.2833
Epoch 8/150
60/60 [==============================] - 0s 85us/step - loss: 0.6386 - acc: 0.2833
Epoch 9/150
60/60 [==============================] - 0s 117us/step - loss: 0.6266 - acc: 0.2833
Epoch 10/150
60/60 [==============================] - 0s 107us/step - loss: 0.6132 - acc: 0.2833
Epoch 11/150
60/60 [========================

In [23]:
# Prediction #
prediction = model.predict(x_test)
prediction = (prediction>0.5)
# prediction.shape
# print(prediction)

# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, prediction)
print(cm)
# Remove the 3rd class #
# Loss function and response variable encoding(y_observed) #

[[ 0 26  0]
 [ 0 33  0]
 [ 0 31  0]]


In [4]:
### SVM using DNN ###

# Defining model #

model = Sequential()
model.add(Dense(1,input_dim=4,activation='linear'))
# model.add(Dense(1,activation='linear'))

# Compile the model #

model.compile(loss='categorical_hinge', optimizer='adam', metrics=['accuracy'])

# Fit the model #

model.fit(X, Y, epochs=150, batch_size=10)

# Evaluate the model #

scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/150
150/150 [==============================] - 0s 736us/step - loss: 14.5943 - acc: 0.0000e+00
Epoch 2/150
150/150 [==============================] - 0s 78us/step - loss: 14.2649 - acc: 0.0000e+00
Epoch 3/150
150/150 [==============================] - 0s 52us/step - loss: 13.9160 - acc: 0.0000e+00
Epoch 4/150
150/150 [==============================] - 0s 69us/step - loss: 13.5840 - acc: 0.0000e+00
Epoch 5/150
150/150 [==============================] - 0s 59us/step - loss: 13.2629 - acc: 0.0000e+00
Epoch 6/150
150/150 [==============================] - 0s 89us/step - loss: 12.9343 - acc: 0.0000e+00
Epoch 7/150
150/150 [==============================] - 0s 57us/step - loss: 12.5969 - acc: 0.0000e+00
Epoch 8/150
150/150 [==============================] - 0s 62us/step - loss: 12.2641 - acc: 0.0000e+00
Epoch 9/150
150/150 [==============================] - 0s 73us/step - loss: 11.9373 - acc: 0.0000e+00
Epoch 10/150
150/150 [==============================] - 0s 69us/step - loss: 11.6